export enum AppRole {
    SUPER_ADMIN           = "SUPER_ADMIN",
    SYSTEM_USER = "SYSTEM_USER",
    USER_ADMINISTRATION_MAKER = "USER_ADMINISTRATION_MAKER",
    USER_ADMINISTRATION_CHECKER = "USER_ADMINISTRATION_CHECKER",
    USER_ADMINISTRATION_VIEWER = "USER_ADMINISTRATION_VIEWER",
    APPLICATION_SYSTEM_ADMINISTRATION_MAKER = "APPLICATION_SYSTEM_ADMINISTRATION_MAKER",
    APPLICATION_SYSTEM_ADMINISTRATION_CHECKER = "APPLICATION_SYSTEM_ADMINISTRATION_CHECKER",
    APPLICATION_SYSTEM_ADMINISTRATION_VIEWER = "APPLICATION_SYSTEM_ADMINISTRATION_VIEWER",
    CUSTOMER_SETUP_MAKER = "CUSTOMER_SETUP_MAKER",
    CUSTOMER_SETUP_CHECKER = "CUSTOMER_SETUP_CHECKER",
    CUSTOMER_SETUP_VIEWER = "CUSTOMER_SETUP_VIEWER",
    EMAILING_TSD_MAKER = "EMAILING_TSD_MAKER",
    EMAILING_TSD_CHECKER = "EMAILING_TSD_CHECKER",
    EMAILING_TSD_VIEWER = "EMAILING_TSD_VIEWER",
    EMAILING_CMO_MAKER = "EMAILING_CMO_MAKER",
    EMAILING_CMO_CHECKER = "EMAILING_CMO_CHECKER",
    EMAILING_CMO_VIEWER = "EMAILING_CMO_VIEWER",

    SIGNATURE_MAKER = "SIGNATURE_MAKER",
    SIGNATURE_APPROVER = "SIGNATURE_APPROVER",

}