## === Log file output ===
#logging.file.name=D:/my git/logs/mshop/mshop.log
## OR (alternative style)
#logging.file.path=D:/my git/logs/mshop
#logging.file.name=mshop.log
#logging.file.max.history=10
#logging.file.max.size=1 MB
#logging.file.total.cap=20 MB
#
## === Rolling policy ===
#logging.logback.rollingpolicy.file-name-pattern=D:/my git/logs/mshop/mshop-%d{yyyy-MM-dd}.%i.log
#logging.logback.rollingpolicy.max-file-size=1MB
#logging.logback.rollingpolicy.total-size-cap=20MB
#logging.logback.rollingpolicy.max-history=10
#
## === Logging levels ===
#logging.level.root=INFO
#logging.level.com.ithouse=DEBUG
#logging.level.org.springframework=INFO
#logging.level.org.hibernate.SQL=WARN
#logging.level.org.apache=WARN
#
## === Pattern and console output ===
##logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %thread [%logger{36}] %msg%n
##logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %thread [%logger{36}] %msg%n
#
## Console pattern (colors)
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%-5level]){faint} %clr(%t){cyan} %clr(%logger{36}){blue} : %m%n
#
## File pattern (no color)
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %thread [%logger{36}:%line] %msg%n
#
##logging.file.path=D:/my git/logs/
##
##logging.file.name=mshop/mshop.log
##logging.include-application-name=true
##logging.logback.rollingpolicy.file-name-pattern=logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log
##logging.logback.rollingpolicy.max-file-size=1MB
##logging.logback.rollingpolicy.total-size-cap=50MB
##logging.logback.rollingpolicy.max-history=10
##
#logging.level.org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration=INFO
#logging.level.org.springframework.boot.actuate.autoconfigure.availability.AvailabilityHealthContributorAutoConfiguration=INFO
#logging.level.org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration=INFO
#
#
#
