export enum Status {
  ANALYST_MODIFIED = "ANALYST_MODIFIED",
  ASSIGNED_2_ANALYST = "ASSIGNED_2_ANALYST",
  MODIFIED = "MODIFIED",
  NEW = "NEW",
  READY_4_ACCEPT = "READY_4_ACCEPT",
  READY_TO_RETAIL = "READY_TO_RETAIL",
  REJECTED = "REJECTED",
  RETAIL_ACCEPTED = "RETAIL_ACCEPTED",
  RETAIL_REJECTED = "RETAIL_REJECTED",
}

export enum Action {
  SAVE = "SAVE",
  SUBMIT = "SUBMIT",
  ACCEPT = "ACCEPT",
  REJECT = "REJECT",
  ASSIGN_2_ANALYST = "ASSIGN_2_ANALYST",
  INITIALIZE_LOAN = "INITIALIZE_LOAN",
}
